import Link from "next/link";
import { Activity, ArrowUpRight, BarChart3, CalendarDays, Eye, Map, MapPin, MessageCircle, Plus, Ticket } from "lucide-react";
import { BrandLogo } from "@/components/site/brand-logo";
import { LogoutButton } from "@/components/admin/logout-button";
import type { AuthUser } from "@/services/auth";
import type { MonitoringSummary } from "@/types/monitoring";

const number = new Intl.NumberFormat("id-ID");

export function AdminFeatureHub({ user, summary, tripCount, voucherCount }: { user: AuthUser; summary: MonitoringSummary; tripCount: number; voucherCount: number }) {
  const conversion = summary.views ? Math.round((summary.whatsappClicks / summary.views) * 100) : 0;
  const leadDestination = summary.destinations[0];
  const stats = [
    { label: "Trip dipublikasikan", value: tripCount, detail: "siap menerima inquiry", icon: Map },
    { label: "Detail trip dilihat", value: summary.views, detail: "30 hari terakhir", icon: Eye },
    { label: "Keberangkatan dipilih", value: summary.departuresSelected, detail: "minat titik jemput", icon: MapPin },
    { label: "Inquiry WhatsApp", value: summary.whatsappClicks, detail: `${conversion}% dari view`, icon: MessageCircle },
  ];

  return <div className="min-h-screen bg-[#e8f1f1] p-3 text-ink sm:p-5 lg:p-7"><div className="mx-auto grid min-h-[calc(100dvh-1.5rem)] max-w-[1480px] overflow-hidden rounded-[2rem] border border-white/80 bg-[#f7fbfb] shadow-[0_28px_80px_rgba(15,75,75,0.12)] lg:grid-cols-[88px_minmax(0,1fr)]">
    <aside className="flex items-center justify-between border-b border-ink/10 bg-white px-5 py-4 lg:flex-col lg:border-b-0 lg:border-r lg:px-3 lg:py-6">
      <Link href="/" className="h-10 w-10" aria-label="Katalog publik E-GOTO"><BrandLogo /></Link>
      <nav className="flex items-center gap-1 lg:flex-col" aria-label="Navigasi admin"><NavItem href="/admin" label="Dashboard" icon={BarChart3} active /><NavItem href="/admin/catalog" label="Trip" icon={Map} /><NavItem href="/admin/vouchers" label="Voucher" icon={Ticket} /><NavItem href="/admin/monitoring" label="Monitoring" icon={Activity} /></nav>
      <Link href="/catalog" className="hidden rounded-xl p-3 text-ink-muted transition hover:bg-primary-soft hover:text-ink lg:inline-flex" aria-label="Buka katalog publik"><ArrowUpRight className="h-5 w-5" /></Link>
    </aside>
    <main className="min-w-0 px-5 py-7 sm:px-8 lg:px-10 lg:py-9">
      <header className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-accent">E-GOTO operations</p><h1 className="mt-2 font-serif text-4xl tracking-[-0.055em] text-ink sm:text-5xl">Dashboard monitoring.</h1><p className="mt-3 text-sm leading-6 text-ink-muted">Lihat minat pelanggan dan lanjutkan ke pengelolaan trip atau voucher.</p><p className="mt-2 text-xs text-ink-muted">{user.email} · {user.role}</p></div><div className="flex flex-wrap items-center gap-3"><div className="flex items-center gap-3 rounded-2xl border border-ink/10 bg-white px-4 py-3 shadow-[0_8px_26px_rgba(25,48,39,0.05)]"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-primary-soft text-accent"><CalendarDays className="h-4 w-4" aria-hidden="true" /></span><span className="text-sm"><span className="block font-bold text-ink">30 hari terakhir</span><span className="block text-xs text-ink-muted">Monitoring aktif</span></span></div><LogoutButton /></div></header>
      <section className="mt-8 grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,0.7fr)]"><article className="relative overflow-hidden rounded-[1.75rem] bg-ink p-7 text-white sm:p-9"><div className="absolute -right-12 -top-16 h-56 w-56 rounded-full border-[30px] border-primary/25" /><div className="absolute -bottom-20 right-20 h-40 w-40 rounded-full border border-white/15" /><div className="relative max-w-xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-primary">Snapshot inquiry</p><h2 className="mt-5 font-serif text-4xl tracking-[-0.055em] sm:text-5xl">{summary.whatsappClicks ? `${number.format(summary.whatsappClicks)} calon pelanggan siap ditindaklanjuti.` : "Mulai pantau inquiry trip Anda."}</h2><p className="mt-5 max-w-lg text-sm leading-6 text-white/70">Data datang dari kunjungan detail trip, pilihan keberangkatan, dan klik WhatsApp.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/admin/monitoring" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-primary px-5 text-sm font-bold text-ink transition hover:bg-white"><BarChart3 className="h-4 w-4" aria-hidden="true" />Lihat monitoring</Link><Link href="/admin/catalog/new" className="inline-flex min-h-11 items-center gap-2 rounded-full border border-white/25 px-5 text-sm font-bold text-white transition hover:bg-white/10"><Plus className="h-4 w-4" aria-hidden="true" />Trip baru</Link></div></div></article><section className="rounded-[1.75rem] border border-ink/10 bg-white p-6 sm:p-7"><p className="text-sm font-bold uppercase tracking-[0.14em] text-accent">Prioritas hari ini</p><h2 className="mt-3 font-serif text-3xl tracking-[-0.045em] text-ink">Area kerja.</h2><div className="mt-6 space-y-3"><QuickLink href="/admin/catalog" icon={Map} title="Kelola trip" detail={`${tripCount} trip tersedia`} /><QuickLink href="/admin/vouchers" icon={Ticket} title="Kelola voucher" detail={`${voucherCount} kode dibuat`} /><QuickLink href="/admin/monitoring" icon={Activity} title="Baca minat" detail={leadDestination ? `${leadDestination.destinationName} teratas` : "Menunggu event pertama"} /></div></section></section>
      <section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Ringkasan metrik">{stats.map((stat) => { const Icon = stat.icon; return <article key={stat.label} className="rounded-[1.35rem] border border-ink/10 bg-white p-5 shadow-[0_10px_28px_rgba(25,48,39,0.045)]"><Icon className="h-5 w-5 text-accent" aria-hidden="true" /><p className="mt-7 text-3xl font-semibold tracking-[-0.055em] text-ink tabular-nums">{number.format(stat.value)}</p><p className="mt-1 text-sm font-semibold text-ink">{stat.label}</p><p className="mt-1 text-xs text-ink-muted">{stat.detail}</p></article>; })}</section>
      <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(280px,0.8fr)]"><section className="rounded-[1.5rem] border border-ink/10 bg-white p-6 sm:p-7"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-accent">Destinasi</p><h2 className="mt-2 font-serif text-3xl tracking-[-0.045em] text-ink">Minat per trip.</h2></div><Link href="/admin/monitoring" className="text-sm font-bold text-accent hover:text-ink">Detail →</Link></div>{summary.destinations.length ? <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[500px] text-left text-sm"><thead className="border-b border-ink/10 text-xs uppercase tracking-[0.12em] text-ink-muted"><tr><th className="pb-3 font-semibold">Trip</th><th className="pb-3 text-right font-semibold">View</th><th className="pb-3 text-right font-semibold">Dipilih</th><th className="pb-3 text-right font-semibold">WhatsApp</th></tr></thead><tbody>{summary.destinations.slice(0, 5).map((destination) => <tr key={destination.destinationId} className="border-b border-ink/8 last:border-0"><td className="py-4 font-semibold text-ink">{destination.destinationName}</td><td className="py-4 text-right tabular-nums text-ink-muted">{number.format(destination.views)}</td><td className="py-4 text-right tabular-nums text-ink-muted">{number.format(destination.departuresSelected)}</td><td className="py-4 text-right font-bold tabular-nums text-ink">{number.format(destination.whatsappClicks)}</td></tr>)}</tbody></table></div> : <p className="mt-6 rounded-2xl bg-paper p-5 text-sm leading-6 text-ink-muted">Belum ada event. Data muncul saat pelanggan membuka detail trip, memilih keberangkatan, atau mengklik WhatsApp.</p>}</section><section className="rounded-[1.5rem] bg-primary-soft p-6 sm:p-7"><p className="text-sm font-bold uppercase tracking-[0.14em] text-accent">Keberangkatan</p><h2 className="mt-2 font-serif text-3xl tracking-[-0.045em] text-ink">Titik diminati.</h2>{summary.departures.length ? <ol className="mt-6 space-y-4">{summary.departures.slice(0, 4).map((departure) => <li key={`${departure.destinationName}-${departure.departureLabel}`} className="flex items-center justify-between gap-4 border-b border-ink/10 pb-4 last:border-0"><span><span className="block font-bold text-ink">{departure.departureLabel}</span><span className="text-xs text-ink-muted">{departure.destinationName}</span></span><span className="text-right text-xs font-bold tabular-nums text-ink-muted">{number.format(departure.selections)} pilih<br />{number.format(departure.whatsappClicks)} WA</span></li>)}</ol> : <p className="mt-6 text-sm leading-6 text-ink-muted">Pilihan titik keberangkatan akan tampil di sini.</p>}</section></section>
    </main>
  </div></div>;
}

function NavItem({ href, label, icon: Icon, active = false }: { href: string; label: string; icon: typeof Map; active?: boolean }) { return <Link href={href} aria-label={label} className={`inline-flex h-11 w-11 items-center justify-center rounded-xl transition ${active ? "bg-ink text-white shadow-[0_7px_16px_rgba(25,48,39,0.18)]" : "text-ink-muted hover:bg-primary-soft hover:text-ink"}`}><Icon className="h-5 w-5" aria-hidden="true" /></Link>; }
function QuickLink({ href, icon: Icon, title, detail }: { href: string; icon: typeof Map; title: string; detail: string }) { return <Link href={href} className="group flex items-center gap-3 rounded-2xl bg-paper p-3 transition hover:bg-primary-soft"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-accent"><Icon className="h-5 w-5" aria-hidden="true" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold text-ink">{title}</span><span className="block truncate text-xs text-ink-muted">{detail}</span></span><ArrowUpRight className="h-4 w-4 text-ink-muted transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:text-ink" aria-hidden="true" /></Link>; }
